spring:
  application:
  name: bai4
  ai:
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: ${OPEN_ROUTER_API_KEY}
      chat:
        model: gpt-oss-20b
    vectorstore:
      pgvector:
        index-type: hnsw
        distance-type: cosine_distance
        dimensions: 1536
        initialize-schema: true